### ISSUE TITLE
move patch fails with large json object

### ISSUE THREAD

**Issue by Truemedia** [dharmafly/jsonpatch.js#29]
Hi,
Iv'e had a library working for a while that uses this library to build a json object from another, as an alternative format.

It has been working fine until my own dataset changed recently.

The following patch seems to trip it up:

```
[ { op: 'move',
    from: '/14',
    path: '/252/nested_classes/0/nested_classes/',
    value: 
     { class_name: 'CreditCard',
       sub_class: 'PaymentMethod',
       properties: {},
       nested_classes: [] } } ]

Error: Path not found in document
```

Now when logging to the console (Doing this in node) the path I get the expected blank array ([]), but why is the patch not seeing the array aswell and applying it? This kind of path has worked in the past, and does still work in multiple instances of my application, just fails with this specific data.

Any thoughts?

**Comment by almost** [comment]
I'm not sure I understand. That doesn't look like a valid patch document, there shouldn't be a "value" field on a  "move" op. What are you expecting it to do?

**Comment by Truemedia** [comment]
Hi thanks for the response. There is a value field if you look carefully (it contains JSON).

This is the extract for the value:

```
value: 
     { class_name: 'CreditCard',
       sub_class: 'PaymentMethod',
       properties: {},
       nested_classes: [] }
```

**Comment by almost** [comment]
But the value is *inside* the patch in a move op which makes no sense to me. Is that an error in the original comment?

**Comment by Truemedia** [comment]
Sorry I know what you mean now. I will double check the output and repost it.
