### ISSUE TITLE
Test passes for objects that are not equal

### ISSUE THREAD

**Issue by brunerd** [dharmafly/jsonpatch.js#42]
The [deepequal](https://github.com/dharmafly/jsonpatch.js/blob/49143e97165d1fee718bf79169696f80d1ebf244/lib/jsonpatch.js#L377) function  has some flaws in it that allows unequal objects to pass a test operation.

I am using jsonpatch.js in my tool [jpt](https://github.com/brunerd/jpt) and came upon this a few weeks ago. The first tip off was when minifying with Google's Closure Compiler I was getting a warning about unreachable code with the for loop on [line 393](https://github.com/dharmafly/jsonpatch.js/blob/49143e97165d1fee718bf79169696f80d1ebf244/lib/jsonpatch.js#L393) and indeed the `i++` is never reached because the next line is `return` on [line 340](https://github.com/dharmafly/jsonpatch.js/blob/49143e97165d1fee718bf79169696f80d1ebf244/lib/jsonpatch.js#L393)

I went ahead and made my changes to get my tool working as expected, I'll just paste in here, vs. doing a pull request and thanks again @almost for your code it is very helpful for rounding out the features in my JSON power tool! 🙏  :]

```
function deepEqual(a,b) {
	var key;
	if (a === b) {
		return true;
	} 
	else if(typeof a !== typeof b) {
		return false;
	}
	else if ('object' === typeof(a)) {
		var aIsArray = isArray(a),
		bIsArray = isArray(b);
		if (aIsArray !== bIsArray) {
			return false;
		} 
		else if (aIsArray) {
			// Both are arrays
			if (a.length != b.length) {
				return false;
			} 
			else {
				for (var i = 0; i < a.length; i++) {
					//original code lacked any conditional for return
					if(! deepEqual(a[i], b[i])){
						return false
					}
				}
				return true
			}
		} 
		//Object - the original code was broken
		else {
			//quickly see if they have the same number of objects
			if (Object.keys(a).length !== Object.keys(b).length) { return false }
							
			// Check each key of the object recursively
			for(key in a) {
				if (!b.hasOwnProperty(key) || ! deepEqual(a[key], b[key])) {
					return false;
				}
			}
			return true;
		}
	} 
	else {
		return false;
	}
}
```

**Comment by almost** [comment]
Thanks! Wow that's quite a bug to have been hanging around this long. I'll make the fix
